apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: c1-jenkins
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
  name: c1-jenkins
  namespace: jenkins
  labels:
    app: c1-jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: c1-jenkins
    targetPort: 8080
  selector:
    app: c1-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-jenkins
  name: c1-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-jenkins
    spec:
      containers:
      - name: c1-jenkins
        image: 527112378451.dkr.ecr.eu-west-1.amazonaws.com/c1-jenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-vol
      volumes:
       - name: jenkins-vol
         persistentVolumeClaim:
           claimName: jenkins-pvc
