apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-jenkins
  name: c1-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-jenkins
    spec:
      containers:
      - name: c1-jenkins
        image: 527112378451.dkr.ecr.eu-west-1.amazonaws.com/c1-jenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-vol
      volumes:
       - name: jenkins-vol
         persistentVolumeClaim:
           claimName: jenkins-pvc
